name: Bot CI-CD CCI PND Demo Deploy

on:
  push:
    branches: [demo]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Getting start notify
        uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            CCI PND Branch : [Demo]
            Getting start to deploy new version.
            ## Please wait till the job is completed ##.

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 20m
          # VPS IP
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}

          script: |
            cd ${{ secrets.PROJECT_PATH_DEMO }}
            # git pull origin demo
            # docker-compose -p demo-cmspndreport -f demo-docker-compose.yml up --build -d --force-recreate
            # echo "Successfully..."
            # docker image prune -a -f

      - name: Final call notify
        uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            CCI PND Branch : [Demo]
            Deploy Successfully...
